# Site settings
author: Tylar Pierson
title: FullStack Web Development 
header-img: img/home-bg.png
email: tylarpiersonbusiness@gmail.com
copyright_name: Tylar Pierson
description: > # this means to ignore newlines until "baseurl:"
  Web Development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tylarpierson

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
